name: Setup tfswitch
description: Sets up tfswitch in your GitHub Actions workflow
branding:
  icon: terminal
  color: purple
inputs:
  github-token:
    description: GitHub token to auth against GitHub's API
    required: true
  tag:
    description: Tag from https://github.com/warrensbox/terraform-switcher/releases
    default: latest
    required: false
runs:
  using: node20
  main: dist/index.js
